config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "admin"

  authenticate :user do
    mount Ckeditor::Engine => '/ckeditor'
  end

  namespace :admin do
    get "/" => "base#index"

    resources :galleries, except: [:show]

    resources :contact_requests, only: [:index, :show, :destroy]
    resources :pages, except: [:show]
    resources :users, except: [:show]
  end

  get "/#{Rails.configuration.x.cms['routes']['contact_requests']}", to: 'contact_requests#new', as: :new_contact
  post "/#{Rails.configuration.x.cms['routes']['contact_requests']}", to: 'contact_requests#create'

  get "/#{Rails.configuration.x.cms['routes']['galleries']}/*slug", to: 'galleries#show', as: :gallery
  get "/#{Rails.configuration.x.cms['routes']['galleries']}", to: 'galleries#show'

  get "sitemap.xml", to: 'sitemaps#generate'

  get '*slug', to: 'pages#show', as: :page
  root 'pages#show', defaults: { slug: "/" }

end

app/models/contact_request.rb
class ContactRequest < ActiveRecord::Base
  validates_presence_of :name, :email, :phone, :body

  validates :name, length: { in: 2..255 }
  validates :email, length: { in: 6..255 }
  validates :phone, length: { is: 9 }
  validates :body, length: { in: 20..255 }

  validates :phone, numericality: { only_integer: true, greater_than: 0 }

  default_scope ->() { order('updated_at DESC') }

  after_create :send_email

  protected

  # Send the information to the notify address after saving the object
  #
  def send_email
    ContactRequestMailer.notify_email(self).deliver_now
  end
end

app/controllers/admin/contact_requests_controller.rb
class Admin::ContactRequestsController < Admin::BaseController
  before_action :load_contact_request, only: [:show, :destroy]

  # Action to list registered contact requests
  #
  def index
    page = params[:page].to_i unless (params[:page].blank? || params[:page].to_i < 1)
    page ||= 1

    max_page = (ContactRequest.count*1.0/ContactRequest.default_per_page).ceil
    max_page = 1 if (max_page == 0)

    page = max_page if (page > max_page)

    # Paginate results
    @contact_requests = ContactRequest.page(page)

    respond_to do |format|
      format.html
    end
  end

  # Action to show a contact request
  #
  def show
    return if @contact_request.blank?

    respond_to do |format|
      format.html
    end
  end

  # Action to destroy a contact request
  #
  def destroy
    return if @contact_request.blank?

    if (@contact_request.destroy)
      flash[:notice] = t(".success", name: @contact_request.name)
    else
      flash[:error] = t(".error", name: @contact_request.name)
    end

    respond_to do |format|
      format.html { redirect_to action: :index }
    end
  end

  protected

  # Before action filter to load the contact request from the DB.
  # If no record is found, redirect to index with an error.
  #
  def load_contact_request
    @contact_request = ContactRequest.where(id: params[:id]).first

    if (@contact_request.blank?)
      flash[:error] = t("admin.contact_requests.not_found")
      redirect_to action: :index
    end
  end
end

app/controllers/contact_requests_controller.rb
class ContactRequestsController < ApplicationController
  before_action :load_page

  # Action to get the form of a new contact request
  #
  def new
    @contact_request = ContactRequest.new()

    respond_to do |format|
      format.html
    end
  end

  # Action to create a new contact request
  #
  def create
    # Avoid duplicates
    @contact_request = ContactRequest.find_or_initialize_by(contact_request_params)

    respond_to do |format|
      format.html {
        if (@contact_request.save)
          flash[:notice] = t(".saved")
          redirect_to action: :new
        else
          flash[:error] = t(".error")
          render action: :new
        end
      }
    end
  end

  protected

  # Try to find the page with contents for the contact views
  # if not found, get a new empty object.
  #
  def load_page
    @page = Page.find_or_initialize_by(slug: Rails.configuration.x.cms['routes']['contact_requests']) || Page.new
  end

  # Strong Paramters filter to get contact request params
  #
  def contact_request_params
    params.require(:contact_request).permit(:name, :email, :phone, :body)
  end
end

app/helpers/admin/contact_requests_helper.rb
module Admin::ContactRequestsHelper
end

app/helpers/contact_requests_helper.rb
module ContactRequestsHelper
end

app/views/contact_requests/new.html.erb
<% unless @page.new_record? %>
<%= content_for :title, (@page.seo_title.blank?) ? @page.title : @page.seo_title %>
<%= content_for :meta_description, @page.seo_description %>
<%= content_for :meta_tags, @page.seo_tags %>
<div class='page-header'>
  <h1 class='title'><%= @page.title %></h1>
  <div class='subtitle'><%= @page.subtitle %></div>
</div>
<%= raw @page.body %>
<% else %>
<p><%= t(".form_info") %></p>
<% end %>

<%= form_for @contact_request, url: new_contact_path(), html: { method: :post, class: 'form-horizontal form-contact' } do |f| %>
<div class='row'>
  <div class='col-sm-offset-2 col-sm-8'>
    <%= bootstrap_flash %>
    <div class="form-group<% unless f.object.errors[:name].blank?%> has-error<% end %>">
      <%= f.label :name, t('.name'), class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, type: 'text', class: 'form-control', placeholder: t('.name_placeholder'), required: true, maxlength: 255 %>
      </div>
    </div>
    <div class="form-group<% unless f.object.errors[:email].blank?%> has-error<% end %>">
      <%= f.label :email, t('.email'), class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :email, type: 'email', class: 'form-control', placeholder: t('.email_placeholder'), required: true, maxlength: 255 %>
      </div>
    </div>
    <div class="form-group<% unless f.object.errors[:phone].blank?%> has-error<% end %>">
      <%= f.label :phone, t('.phone'), class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.number_field :phone, class: 'form-control', placeholder: t('.phone_placeholder'), required: true, min: 100000000, max: 999999999, step: 1 %>
      </div>
    </div>
    <div class="form-group<% unless f.object.errors[:body].blank?%> has-error<% end %>">
      <%= f.label :body, t('.body'), class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :body, class: 'form-control', placeholder: t('.body_placeholder'), required: true, maxlength: 255, minlength: 20 %>
        <p class="help-block"><%= t(".body_help") %></p>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= button_tag "#{t(".submit")}&nbsp;&nbsp;<i class='fa fa-chevron-right'></i>".html_safe, type: :submit, class: 'btn btn-success'%>
      </div>
    </div>
  </div>
</div>
<% end %>