config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "admin"

  authenticate :user do
    mount Ckeditor::Engine => '/ckeditor'
  end

  namespace :admin do
    get "/" => "base#index"

    resources :galleries, except: [:show]

    resources :contact_requests, only: [:index, :show, :destroy]
    resources :pages, except: [:show]
    resources :users, except: [:show]
  end

  get "/#{Rails.configuration.x.cms['routes']['contact_requests']}", to: 'contact_requests#new', as: :new_contact
  post "/#{Rails.configuration.x.cms['routes']['contact_requests']}", to: 'contact_requests#create'

  get "/#{Rails.configuration.x.cms['routes']['galleries']}/*slug", to: 'galleries#show', as: :gallery
  get "/#{Rails.configuration.x.cms['routes']['galleries']}", to: 'galleries#show'

  get "sitemap.xml", to: 'sitemaps#generate'

  get '*slug', to: 'pages#show', as: :page
  root 'pages#show', defaults: { slug: "/" }

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title><%= content_for?(:title) ? "#{yield(:title)} - " : "" %><%= t(".title") %></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= yield :header_tags %>

    <%= stylesheet_link_tag   'admin', media: 'all' %>
    <%= csrf_meta_tags %>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to t('.navbar.brand_name'), admin_path(), class: 'navbar-brand' %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% Rails.configuration.x.cms['menu_items'].map(&:controller_name).each do |c| %>
            <li<% if (controller_name == c) %> class="active"<% end %>>
              <%= link_to t(".navbar.elements.#{c}"), url_for(controller: c, action: :index) %>
            </li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to t(".navbar.view_site"), root_path() %></li>
            <li class="dropdown">
              <%= link_to "#{current_user.email}&nbsp;<span class='caret'></span>".html_safe, '#', class: "dropdown-toggle", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': true, 'aria-expanded': false %>
              <ul class="dropdown-menu">
                <li><%= link_to "<i class='fa fa-user'></i>&nbsp;&nbsp;#{t('.navbar.user.edit')}".html_safe, edit_admin_user_path(id: current_user.id) %></a></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "<i class='fa fa-sign-out'></i>&nbsp;&nbsp;#{t('.navbar.user.sign_out')}".html_safe, destroy_user_session_path(), method: :delete %></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>

    <footer>
      <div class="container">
        <p><%= t(".footer.text_html", year: Time.now.year) %></p>
      </div>
    </footer>

    <%= javascript_include_tag 'admin' %>

    <script type="text/javascript">
    $(function() {
      CKEDITOR.config.customConfig = '<%= asset_path('config.js') %>';
    });
    </script>

    <%= javascript_include_tag Ckeditor.cdn_url %>
    <%= yield :javascripts %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title><%= content_for?(:title) ? "#{yield(:title)} - " : "" %><%= t("sitename") %></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="<%= I18n.locale %>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name='description' content='<%= content_for?(:meta_description) ? "#{yield(:meta_description)}" : t('.default_seo.description') %>'/>
    <meta name='keywords' content='<%= content_for?(:meta_keywords) ? "#{yield(:meta_keywords)}" : t('.default_seo.keywords') %>'/>
    <meta name='robots' content='index, follow' />
    <meta name="google-site-verification" content="Z8jk2blvUcJdxsiME9VymHukbD1LFAVPwYmW814tOn8" />

    <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/favicon-194x194.png" sizes="194x194">
    <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/manifest.json">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="apple-mobile-web-app-title" content="Capitel VII">
    <meta name="application-name" content="Capitel VII">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-TileImage" content="/mstile-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <%= yield :header_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>
    <%= render partial: 'shared/header' %>

    <div class="container content">
      <%= yield %>
    </div>

    <%= render partial: 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= yield :javascripts %>

    <script type="text/javascript">
      window.onload = function() {
        CPC.init({
          msg: '<p><b>Aviso de cookies</b>: este sitio web utiliza cookies para su funcionamiento (<a href="<%= page_path(slug: Rails.configuration.x.cms['routes']['cookies']) %>">más información</a>).<br /><a href="#" id="cookie-policy-consent-close">Acepto el uso de cookies</a></p>',
          load_external_files: false
        });
      };
      <% unless (Rails.application.secrets.analytics_id.blank? || user_signed_in?) %>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', '<%= Rails.application.secrets.analytics_id %>', 'auto');
      ga('send', 'pageview');
      <% end %>
    </script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title><%= content_for?(:title) ? "#{yield(:title)} - " : "" %><%= t(".title") %></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= yield :header_tags %>

    <%= stylesheet_link_tag   'devise', media: 'all' %>
    <%= csrf_meta_tags %>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>
    <div class="container form-devise">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= yield :javascripts %>
  </body>
</html>